#language: generic    # if travis build fails with "rakefile not found"
sudo: required
services:
  - docker

before_install:
  - docker build -t chakrimohamed:react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chakrimohamed:react-test npm test -- --coverage		 # coverage for exit and end the test

after_success:
  - docker build -t chakriMohamed/multi-client ./client
  - docker build -t chakriMohamed/multi-nginx ./nginx
  - docker build -t chakriMohamed/multi-server ./server
  - docker build -t chakriMohamed/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push chakriMohamed/multi-client
  - docker push chakriMohamed/multi-nginx
  - docker push chakriMohamed/multi-server
  - docker push chakriMohamed/multi-worker

